apiVersion: v1
kind: Namespace
metadata:
  name: palworld
  labels:
    name: palworld
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-pvc
  namespace: palworld
  labels:
    app: palworld
    owner: saitcho
    name: palworld-volume
spec:
  storageClassName: "microk8s-hostpath"
  volumeName: palworld-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: palworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
      - image: ghcr.io/dkirby-ms/palworld:master
        name: palworld-server
        command: ["/bin/bash", "entry.sh"]
        volumeMounts:
        - name: palworld-data
          mountPath: /data/palworld
        resources:
          requests:
            cpu: "500m"
            memory: "2G"
          limits:
            cpu: "1000m"
            memory: "4G"
      volumes:
        - name: palworld-data
          persistentVolumeClaim:
            claimName: palworld-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: palworld
spec:
  type: NodePort
  selector:
    app: palworld-server
  ports:
  - protocol: UDP
    port: 14159
    targetPort: 14159
