apiVersion: v1
kind: Namespace
metadata:
  name: palworld
  labels:
    name: palworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: palworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
      - image: cm2network/steamcmd:latest
        name: palworld-server
        command: ["/bin/sh", "-c", "/data/launch_server.sh"]
        volumeMounts:
        - name: palworld-data
          mountPath: /data
        resources:
          requests:
            cpu: "500m"
            memory: "2G"
          limits:
            cpu: "1000m"
            memory: "4G"
      volumes:
        - name: palworld-data
          hostPath:
            path: /opt/palworld-data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: palworld
spec:
  type: NodePort
  selector:
    app: palworld-server
  ports:
  - protocol: UDP
    port: 8211
    targetPort: 8211
